export const COMPILE_CSD = "COMPILE_CSD";
export const START_PERFORMANCE = "START_PERFORMANCE";
export const CSOUND_INITIALIZED = "CSOUND_INITIALIZED";
const WRITE_TO_FS = "WRITE_TO_FS";
const UNLINK_FROM_FS = "UNLINK_FROM_FS";
const SET_OUTPUT_CHANNEL_CALLBACK = "SET_OUTPUT_CHANNEL_CALLBACK";
const SET_INPUT_CHANNEL_CALLBACK = "SET_INPUT_CHANNEL_CALLBACK";
const SET_INPUT_CHANNEL_VALUE = "SET_INPUT_CHANNEL_VALUE";
const SEND_OUTPUT_CHANNEL_VALUE = "SEND_OUTPUT_CHANNEL_VALUE";
const SEND_MIDI_MESSAGE = "SEND_MIDI_MESSAGE";
const SET_CONTROL_CHANNEL = "SET_CONTROL_CHANNEL";
export default {
    COMPILE_CSD,
    CSOUND_INITIALIZED,
    START_PERFORMANCE,
    WRITE_TO_FS,
    UNLINK_FROM_FS,
    SET_OUTPUT_CHANNEL_CALLBACK,
    SET_INPUT_CHANNEL_CALLBACK,
    SET_INPUT_CHANNEL_VALUE,
    SEND_OUTPUT_CHANNEL_VALUE,
    SEND_MIDI_MESSAGE,
    SET_CONTROL_CHANNEL
};
