export const COMPILE_CSD = "COMPILE_CSD";
export const START_PERFORMANCE = "START_PERFORMANCE";
export const CSOUND_INITIALIZED = "CSOUND_INITIALIZED";
export const WRITE_TO_FS = "WRITE_TO_FS";
export const UNLINK_FROM_FS = "UNLINK_FROM_FS";
export const SET_OUTPUT_CHANNEL_CALLBACK = "SET_OUTPUT_CHANNEL_CALLBACK";
export const SEND_OUTPUT_CHANNEL_VALUE = "SEND_OUTPUT_CHANNEL_VALUE";
export default {
    COMPILE_CSD,
    CSOUND_INITIALIZED,
    START_PERFORMANCE,
    WRITE_TO_FS,
    UNLINK_FROM_FS,
    SET_OUTPUT_CHANNEL_CALLBACK,
    SEND_OUTPUT_CHANNEL_VALUE
};
